baseURL = "https://lobban.org"
languageCode = "en-us"
title = "Andy Lobban"
theme = "lobban"
description = ""
Paginate = 10
uglyURLs = false

[Params]
  title = "Andy Lobban"
  RSSLink = "/index.xml"
  author = "Andy Lobban"
  locale = "en-GB"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
    categories = "/posts/category/:slug/"
