baseURL = ""
languageCode = "en-gb"
title = "Andy Lobban"
theme = "lobban"
description = ""
Paginate = 10
uglyURLs = false
enableRobotsTXT = true

[Params]
    disallow_search_engines = false
    title = "Andy Lobban"
    RSSLink = "/index.xml"
    author = "Andy Lobban"
    locale = "en-GB"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
    categories = "/posts/category/:slug/"
