[build]
    command = "hugo"
    publish = "public"
    functions = "functions"

[build.environment]
    HUGO_VERSION = "0.54.0"

[context.production.environment]
    HUGO_ENV = "production"

[[redirects]]
    from = "/about"
    to = "/info"
    status = 301

[[redirects]]
    from = "/contact"
    to = "/info"
    status = 301

[[redirects]]
    from = "/journal/*"
    to = "/posts/:splat"
    status = 301
